### PR TITLE
Initial version of action-helm-sbom-upload (#1)

### PR DESCRIPTION
**Pull request by medcrypt-matt**
* first full working version of the SBOM upload action. To be tagged version 1.0.0

This is simply merging dev (previously approved changes) into main/master

### CODE REVIEW

**Comment by harithamc** [comment]
looks good

**Comment by harithamc** [comment]
I don't see an approval button for some reason.

**Comment by medcrypt-matt** [comment]
> I don't see an approval button for some reason.

@harithamc how about now? I'm still trying to figure out "assignees" vs "reviewers" and why they are different.

**Review by harithamc — APPROVED** [review]
Looks good!

**Review by DanBeardMC — APPROVED** [review]

**Pull request merged**
